name = "google"
main = "dist/index.js"
compatibility_date = "2024-05-01"

[build]
command = "npm run build"

[vars]
# GOOGLE_CLIENT_ID = ""
# GOOGLE_CLIENT_SECRET = ""
# allowed to define environment variables externally

# Example KV binding for token storage
# [[kv_namespaces]]
# binding = "TOKENS"
# id = "00000000000000000000000000000000000"
