name = "google-worker"
main = "dist/index.mjs"
compatibility_date = "2024-05-01"

[vars]
# GOOGLE_CLIENT_ID = ""
# GOOGLE_CLIENT_SECRET = ""
# allowed to define environment variables externally

[kv_namespaces]
# Example KV binding for token storage
# binding = "TOKENS"
# id = "00000000000000000000000000000000000"
